/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Organization.TransportScreens;

import Organization.Hospitals.HospitalMain;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author aesha
 */
public class TransportAvailability extends javax.swing.JPanel {

    /**
     * Creates new form TransportAvailability
     */
    private JPanel RightPanel;
    static Logger log = Logger.getLogger(TransportAvailability.class.getName());

    public TransportAvailability(JPanel RightPanel) {
        initComponents();
        this.RightPanel = RightPanel;
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schema1?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root12345");
            Statement myStatement = con.createStatement();

            String querysel = "Select * from FinalProj_Vehicles";
            ResultSet rs = myStatement.executeQuery(querysel);
            //cmbStore.removeAllItems();
            model.setRowCount(0);
            while (rs.next()) {
                //cmbStore.addItem(rs.getString("StoreName"));
                String StoreName1 = rs.getString("StoreName");
                String Ambulance1 = rs.getString("Ambulance");
                String Truck1 = rs.getString("Truck");
                String Travel1 = rs.getString("Travel");
                String Lastupdated = rs.getString("Lastupdated");

                Object row[] = new Object[5];
                row[0] = StoreName1;
                row[1] = Ambulance1;
                row[2] = Truck1;
                row[3] = Travel1;
                row[4] = Lastupdated;
                model.addRow(row);
            }
            con.close();
        } //System.out.println("Inserted data");
        catch (Exception E) {
            JOptionPane.showMessageDialog(this, "Error in DB connection");
            log.error("Error in DB connection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAmbulance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTruck = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTravel = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtStoreName = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VEHICLE AVAILABILITY");

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "StoreName", "Travel Vehicles", "Ambulance", "Truck", "LastUpdated"
            }
        ));
        jScrollPane1.setViewportView(tblVehicles);

        jLabel3.setText("StoreName:");

        jLabel2.setText("Ambulance:");

        jLabel4.setText("Truck:");

        jLabel5.setText("Travel Vehicles:");

        btnUpdate.setBackground(new java.awt.Color(102, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(102, 153, 255));
        btnCreate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 153, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 384, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(btnUpdate))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCreate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmbulance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTruck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTravel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(420, 420, 420))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnDelete, btnUpdate});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnCreate)
                    .addComponent(btnDelete))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtStoreName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter value .");
            return;
        } else {
            String Ambulance = txtAmbulance.getText();
            String Truck = txtTruck.getText();
            String Travel = txtTravel.getText();
            String StoreName = txtStoreName.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String Date = dateFormat.format(java.util.Calendar.getInstance().getTime());
            DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schema1?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root12345");
                Statement myStatement = con.createStatement();

                String query = "Update FinalProj_Vehicles set Ambulance ='" + Ambulance + "',Truck ='" + Truck + "',Lastupdated ='" + Date + "', Travel ='" + Travel + "' where StoreName='" + StoreName + "'";
                myStatement.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Entry Updated!!");
                log.info("Entry Updated!!");

                String querysel = "Select * from FinalProj_Vehicles";
                ResultSet rs = myStatement.executeQuery(querysel);
                //cmbStore.removeAllItems();
                model.setRowCount(0);
                while (rs.next()) {
                    //cmbStore.addItem(rs.getString("StoreName"));
                    String StoreName1 = rs.getString("StoreName");
                    String Ambulance1 = rs.getString("Ambulance");
                    String Truck1 = rs.getString("Truck");
                    String Travel1 = rs.getString("Travel");
                    String Lastupdated = rs.getString("Lastupdated");

                    Object row[] = new Object[5];
                    row[0] = StoreName1;
                    row[1] = Ambulance1;
                    row[2] = Truck1;
                    row[3] = Travel1;
                    row[4] = Lastupdated;
                    model.addRow(row);
                }
                con.close();
            } //System.out.println("Inserted data");
            catch (Exception E) {
                JOptionPane.showMessageDialog(this, "Error in DB connection");
                log.error("Error in DB connection");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtStoreName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter value .");
            return;
        } else {
            String Ambulance = txtAmbulance.getText();
            String Truck = txtTruck.getText();
            String Travel = txtTravel.getText();
            String StoreName = txtStoreName.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String Date = dateFormat.format(java.util.Calendar.getInstance().getTime());
            DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schema1?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root12345");
                Statement myStatement = con.createStatement();

                String query = "Insert into `FinalProj_Vehicles`" + "values('" + StoreName + "','" + Ambulance + "','" + Truck + "','" + Travel + "','" + Date + "')";
                myStatement.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Record Inserted!!");
                log.info("Record Inserted!!");

                String querysel = "Select * from FinalProj_Vehicles";
                ResultSet rs = myStatement.executeQuery(querysel);
                //cmbStore.removeAllItems();
                model.setRowCount(0);
                while (rs.next()) {
                    //cmbStore.addItem(rs.getString("StoreName"));
                    String StoreName1 = rs.getString("StoreName");
                    String Ambulance1 = rs.getString("Ambulance");
                    String Truck1 = rs.getString("Truck");
                    String Travel1 = rs.getString("Travel");
                    String Lastupdated = rs.getString("Lastupdated");

                    Object row[] = new Object[5];
                    row[0] = StoreName1;
                    row[1] = Travel1;
                    row[2] = Ambulance1;
                    row[3] = Truck1;
                    row[4] = Lastupdated;
                    model.addRow(row);
                }
                con.close();
            } //System.out.println("Inserted data");
            catch (Exception E) {
                JOptionPane.showMessageDialog(this, "Error in DB connection");
                log.error("Error in DB connection");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (txtStoreName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter value .");
            return;
        } else {
            String Ambulance = txtAmbulance.getText();
            String Truck = txtTruck.getText();
            String Travel = txtTravel.getText();
            String StoreName = txtStoreName.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String Date = dateFormat.format(java.util.Calendar.getInstance().getTime());
            DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schema1?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root12345");
                Statement myStatement = con.createStatement();

                String query = "Delete from `FinalProj_Vehicles` where `StoreName`='" + StoreName + "'";
                myStatement.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Record Deleted!!");
                log.info("Record Deleted!!");

                String querysel = "Select * from FinalProj_Vehicles";
                ResultSet rs = myStatement.executeQuery(querysel);
                //cmbStore.removeAllItems();
                model.setRowCount(0);
                while (rs.next()) {
                    //cmbStore.addItem(rs.getString("StoreName"));
                    String StoreName1 = rs.getString("StoreName");
                    String Ambulance1 = rs.getString("Ambulance");
                    String Truck1 = rs.getString("Truck");
                    String Travel1 = rs.getString("Travel");
                    String Lastupdated = rs.getString("Lastupdated");

                    Object row[] = new Object[5];
                    row[0] = StoreName1;
                    row[1] = Travel1;
                    row[2] = Ambulance1;
                    row[3] = Truck1;
                    row[4] = Lastupdated;
                    model.addRow(row);
                }
                con.close();
            } //System.out.println("Inserted data");
            catch (Exception E) {
                JOptionPane.showMessageDialog(this, "Error in DB connection");
                log.error("Error in DB connection");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField txtAmbulance;
    private javax.swing.JTextField txtStoreName;
    private javax.swing.JTextField txtTravel;
    private javax.swing.JTextField txtTruck;
    // End of variables declaration//GEN-END:variables
}
