/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author anvithalakshmisha
 */
public class OrgPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrgPanel
     */
    String selectedOrg;

    public OrgPanel(String selectedOrg) {
        initComponents();
        this.selectedOrg = selectedOrg;
        if (this.selectedOrg == "Hospitals") {
            panelForDisplay(panelHospital);
        } else if (this.selectedOrg == "Vaccine manufacturer") {
            panelForDisplay(panelVaccine);
        } else if (this.selectedOrg == "Blood bank") {
            panelForDisplay(panelBloodbank);
        } else if (this.selectedOrg == "Medical equipment") {
            panelForDisplay(panelMedicalEquip);
        } else if (this.selectedOrg == "Insurance") {
            panelForDisplay(panelInsurance);
        } else if (this.selectedOrg == "Food market chains") {
            panelForDisplay(panelFoodbank);
        } else if (this.selectedOrg == "Clothing retailers") {
            panelForDisplay(panelClothing);
        } else if (this.selectedOrg == "Transport/Travel agencies") {
            panelForDisplay(panelTransportation);
        }
        comboBoxBloodGroup.removeAllItems();;
        comboBoxBloodGroup.addItem("A positive");
        comboBoxBloodGroup.addItem("A negative");
        comboBoxBloodGroup.addItem("B positive");
        comboBoxBloodGroup.addItem("B negative");
        comboBoxBloodGroup.addItem("O positive");
        comboBoxBloodGroup.addItem("O negative");
        comboBoxBloodGroup.addItem("AB positive");
        comboBoxBloodGroup.addItem("AB negative");

    }

    private void panelForDisplay(Component component) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(component);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelHospital = new javax.swing.JPanel();
        lblHospitalInventory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumberOfBeds = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHospitalLoc = new javax.swing.JTextField();
        btnSendRequestHospital = new javax.swing.JButton();
        panelVaccine = new javax.swing.JPanel();
        lblVaccineInventory1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVaccine = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVaccineCount = new javax.swing.JTextField();
        btnSendRequestVaccine = new javax.swing.JButton();
        panelMedicalEquip = new javax.swing.JPanel();
        lbMedicalEqupInventory = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMedicalEquip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMedicalEquipCount = new javax.swing.JTextField();
        btnSendRequestMedicalEquip = new javax.swing.JButton();
        panelBloodbank = new javax.swing.JPanel();
        lblBloodbankInventory = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBloodCount = new javax.swing.JTextField();
        btnSendRequestBloodbank = new javax.swing.JButton();
        comboBoxBloodGroup = new javax.swing.JComboBox<>();
        panelInsurance = new javax.swing.JPanel();
        lblVaccineInventory2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInsuranceCoverage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumberOfCoverage = new javax.swing.JTextField();
        btnSubmitRequestInsurance = new javax.swing.JButton();
        panelFoodbank = new javax.swing.JPanel();
        lblFoodbankInventory = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFoodBankServed = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFoodBankLoc = new javax.swing.JTextField();
        btnSendRequestFoodbank = new javax.swing.JButton();
        panelTransportation = new javax.swing.JPanel();
        lblFoodbankInventory1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVehicleType = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtVehicleCount = new javax.swing.JTextField();
        btnSendRequestTransportation = new javax.swing.JButton();
        panelClothing = new javax.swing.JPanel();
        lblFoodbankInventory2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNumberOfClothing1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtClothingLoc1 = new javax.swing.JTextField();
        btnSendRequestClothing = new javax.swing.JButton();

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        lblHospitalInventory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblHospitalInventory.setForeground(new java.awt.Color(51, 153, 255));
        lblHospitalInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalInventory.setText("Hospital Inventory");

        jLabel1.setText("Enter the number of beds required :");

        txtNumberOfBeds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumberOfBedsFocusLost(evt);
            }
        });

        jLabel2.setText("Enter the location :");

        btnSendRequestHospital.setText("Send request");
        btnSendRequestHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestHospitalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHospitalLayout = new javax.swing.GroupLayout(panelHospital);
        panelHospital.setLayout(panelHospitalLayout);
        panelHospitalLayout.setHorizontalGroup(
            panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospitalInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelHospitalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHospitalLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberOfBeds, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHospitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestHospital)
                .addGap(175, 175, 175))
        );

        panelHospitalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHospitalLoc, txtNumberOfBeds});

        panelHospitalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        panelHospitalLayout.setVerticalGroup(
            panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospitalInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumberOfBeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHospitalLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestHospital)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelHospital, "card2");

        lblVaccineInventory1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblVaccineInventory1.setForeground(new java.awt.Color(51, 153, 255));
        lblVaccineInventory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaccineInventory1.setText("Vaccine Inventory");

        jLabel3.setText("Enter the vaccine required :");

        jLabel4.setText("Enter the number of vaccine required  :");

        txtVaccineCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVaccineCountFocusLost(evt);
            }
        });

        btnSendRequestVaccine.setText("Send request");
        btnSendRequestVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestVaccineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVaccineLayout = new javax.swing.GroupLayout(panelVaccine);
        panelVaccine.setLayout(panelVaccineLayout);
        panelVaccineLayout.setHorizontalGroup(
            panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVaccineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVaccineInventory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelVaccineLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVaccineCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVaccineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestVaccine)
                .addGap(175, 175, 175))
        );

        panelVaccineLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtVaccine, txtVaccineCount});

        panelVaccineLayout.setVerticalGroup(
            panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVaccineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVaccineInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVaccineCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestVaccine)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelVaccine, "card2");

        lbMedicalEqupInventory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lbMedicalEqupInventory.setForeground(new java.awt.Color(51, 153, 255));
        lbMedicalEqupInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMedicalEqupInventory.setText("Medical Euipment Inventory");

        jLabel5.setText("Enter the medical equipment required :");

        jLabel6.setText("Enter the count :");

        txtMedicalEquipCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedicalEquipCountFocusLost(evt);
            }
        });
        txtMedicalEquipCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalEquipCountActionPerformed(evt);
            }
        });

        btnSendRequestMedicalEquip.setText("Send request");
        btnSendRequestMedicalEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestMedicalEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMedicalEquipLayout = new javax.swing.GroupLayout(panelMedicalEquip);
        panelMedicalEquip.setLayout(panelMedicalEquipLayout);
        panelMedicalEquipLayout.setHorizontalGroup(
            panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicalEquipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMedicalEqupInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMedicalEquipLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicalEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalEquipCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedicalEquipLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestMedicalEquip)
                .addGap(175, 175, 175))
        );

        panelMedicalEquipLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtMedicalEquip, txtMedicalEquipCount});

        panelMedicalEquipLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6});

        panelMedicalEquipLayout.setVerticalGroup(
            panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicalEquipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMedicalEqupInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMedicalEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMedicalEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMedicalEquipCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestMedicalEquip)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelMedicalEquip, "card2");

        lblBloodbankInventory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBloodbankInventory.setForeground(new java.awt.Color(51, 153, 255));
        lblBloodbankInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBloodbankInventory.setText("Bloodbank Inventory");

        jLabel7.setText("Select the blood group required :");

        jLabel8.setText("Enter the count :");

        txtBloodCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBloodCountFocusLost(evt);
            }
        });

        btnSendRequestBloodbank.setText("Send request");
        btnSendRequestBloodbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestBloodbankActionPerformed(evt);
            }
        });

        comboBoxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelBloodbankLayout = new javax.swing.GroupLayout(panelBloodbank);
        panelBloodbank.setLayout(panelBloodbankLayout);
        panelBloodbankLayout.setHorizontalGroup(
            panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBloodbankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBloodbankInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelBloodbankLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBloodCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBloodbankLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestBloodbank)
                .addGap(175, 175, 175))
        );

        panelBloodbankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8});

        panelBloodbankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboBoxBloodGroup, txtBloodCount});

        panelBloodbankLayout.setVerticalGroup(
            panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBloodbankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBloodbankInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelBloodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBloodCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestBloodbank)
                .addGap(199, 199, 199))
        );

        jLayeredPane1.add(panelBloodbank, "card2");

        lblVaccineInventory2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblVaccineInventory2.setForeground(new java.awt.Color(51, 153, 255));
        lblVaccineInventory2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaccineInventory2.setText("Insurance Inventory");

        jLabel9.setText("Enter the insurance coverage required :");

        txtInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceCoverageActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter the number of such coverage(s) required  :");

        txtNumberOfCoverage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumberOfCoverageFocusLost(evt);
            }
        });

        btnSubmitRequestInsurance.setText("Send request");
        btnSubmitRequestInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestInsuranceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInsuranceLayout = new javax.swing.GroupLayout(panelInsurance);
        panelInsurance.setLayout(panelInsuranceLayout);
        panelInsuranceLayout.setHorizontalGroup(
            panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsuranceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVaccineInventory2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelInsuranceLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberOfCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInsuranceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitRequestInsurance)
                .addGap(175, 175, 175))
        );

        panelInsuranceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel9});

        panelInsuranceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInsuranceCoverage, txtNumberOfCoverage});

        panelInsuranceLayout.setVerticalGroup(
            panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsuranceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVaccineInventory2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumberOfCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSubmitRequestInsurance)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelInsurance, "card2");

        lblFoodbankInventory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblFoodbankInventory.setForeground(new java.awt.Color(51, 153, 255));
        lblFoodbankInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoodbankInventory.setText("Foodbank Inventory");

        jLabel11.setText("Enter the number of people to be served :");

        txtFoodBankServed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFoodBankServedFocusLost(evt);
            }
        });

        jLabel12.setText("Enter the location :");

        btnSendRequestFoodbank.setText("Send request");
        btnSendRequestFoodbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestFoodbankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFoodbankLayout = new javax.swing.GroupLayout(panelFoodbank);
        panelFoodbank.setLayout(panelFoodbankLayout);
        panelFoodbankLayout.setHorizontalGroup(
            panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFoodbankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFoodbankLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFoodBankLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFoodBankServed, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFoodbankLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestFoodbank)
                .addGap(175, 175, 175))
        );

        panelFoodbankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12});

        panelFoodbankLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFoodBankLoc, txtFoodBankServed});

        panelFoodbankLayout.setVerticalGroup(
            panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFoodbankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFoodBankServed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFoodbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFoodBankLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestFoodbank)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelFoodbank, "card2");

        lblFoodbankInventory1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblFoodbankInventory1.setForeground(new java.awt.Color(51, 153, 255));
        lblFoodbankInventory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoodbankInventory1.setText("Transportation Inventory");

        jLabel13.setText("Enter the type of vehicle required :");

        jLabel14.setText("Enter the count :");

        txtVehicleCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleCountFocusLost(evt);
            }
        });

        btnSendRequestTransportation.setText("Send request");
        btnSendRequestTransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestTransportationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransportationLayout = new javax.swing.GroupLayout(panelTransportation);
        panelTransportation.setLayout(panelTransportationLayout);
        panelTransportationLayout.setHorizontalGroup(
            panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransportationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelTransportationLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVehicleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransportationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestTransportation)
                .addGap(175, 175, 175))
        );

        panelTransportationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtVehicleCount, txtVehicleType});

        panelTransportationLayout.setVerticalGroup(
            panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransportationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTransportationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtVehicleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestTransportation)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelTransportation, "card2");

        lblFoodbankInventory2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblFoodbankInventory2.setForeground(new java.awt.Color(51, 153, 255));
        lblFoodbankInventory2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoodbankInventory2.setText("Clothing Inventory");

        jLabel15.setText("Enter the number of people to be served :");

        txtNumberOfClothing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumberOfClothing1FocusLost(evt);
            }
        });

        jLabel16.setText("Enter the location :");

        btnSendRequestClothing.setText("Send request");
        btnSendRequestClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestClothingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClothingLayout = new javax.swing.GroupLayout(panelClothing);
        panelClothing.setLayout(panelClothingLayout);
        panelClothingLayout.setHorizontalGroup(
            panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClothingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelClothingLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClothingLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberOfClothing1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClothingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendRequestClothing)
                .addGap(175, 175, 175))
        );

        panelClothingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtClothingLoc1, txtNumberOfClothing1});

        panelClothingLayout.setVerticalGroup(
            panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClothingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodbankInventory2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNumberOfClothing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtClothingLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnSendRequestClothing)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelClothing, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestHospitalActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtHospitalLoc.getText().isEmpty()) {
        } else {
            Error.append("Enter Hospital Location \n");
        }
        if (!txtNumberOfBeds.getText().isEmpty()) {
        } else {
            Error.append("Enter Number of beds \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtNumberOfBeds.setText("");
            txtHospitalLoc.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for hospital beds has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestHospitalActionPerformed

    private void btnSendRequestVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestVaccineActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtVaccine.getText().isEmpty()) {
        } else {
            Error.append("Enter vaccine required \n");
        }
        if (!txtVaccineCount.getText().isEmpty()) {
        } else {
            Error.append("Enter the vaccine count \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtVaccineCount.setText("");
            txtVaccine.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for vaccine has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestVaccineActionPerformed

    private void btnSendRequestMedicalEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestMedicalEquipActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtMedicalEquip.getText().isEmpty()) {
        } else {
            Error.append("Enter equipment required \n");
        }
        if (!txtMedicalEquipCount.getText().isEmpty()) {
        } else {
            Error.append("Enter the equipment count \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtMedicalEquip.setText("");
            txtMedicalEquipCount.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for medical equipment has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestMedicalEquipActionPerformed

    private void btnSendRequestBloodbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestBloodbankActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (comboBoxBloodGroup.getSelectedIndex() != -1) {
        } else {
            Error.append("Select the blood group  \n");
        }
        if (!txtBloodCount.getText().isEmpty()) {
        } else {
            Error.append("Enter the count \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
//            comboBoxBloodGroup.rem"");
            txtBloodCount.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for blood has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestBloodbankActionPerformed

    private void btnSubmitRequestInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestInsuranceActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtInsuranceCoverage.getText().isEmpty()) {
        } else {
            Error.append("Enter insurance coverage required \n");
        }
        if (!txtNumberOfCoverage.getText().isEmpty()) {
        } else {
            Error.append("Enter insurance coverage count \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtInsuranceCoverage.setText("");
            txtNumberOfCoverage.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for insurance coverage has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSubmitRequestInsuranceActionPerformed

    private void btnSendRequestFoodbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestFoodbankActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtFoodBankServed.getText().isEmpty()) {
        } else {
            Error.append("Enter number of people to be served \n");
        }
        if (!txtFoodBankLoc.getText().isEmpty()) {
        } else {
            Error.append("Enter location \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtFoodBankLoc.setText("");
            txtFoodBankServed.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for food items has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestFoodbankActionPerformed

    private void btnSendRequestTransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestTransportationActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtVehicleType.getText().isEmpty()) {
        } else {
            Error.append("Enter vehicle type \n");
        }
        if (!txtVehicleCount.getText().isEmpty()) {
        } else {
            Error.append("Enter number of vehicles required \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtVehicleCount.setText("");
            txtVehicleType.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for vehicles has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestTransportationActionPerformed

    private void btnSendRequestClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestClothingActionPerformed
        // TODO add your handling code here:
        StringBuilder Error = new StringBuilder();
        if (!txtClothingLoc1.getText().isEmpty()) {
        } else {
            Error.append("Enter location \n");
        }
        if (!txtNumberOfClothing1.getText().isEmpty()) {
        } else {
            Error.append("Enter number of people to be served \n");
        }
        if (Error.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Request created");
            txtNumberOfClothing1.setText("");
            txtClothingLoc1.setText("");
            Business.SendMail mail = new Business.SendMail();
            mail.sendMail("Request created", "Your request for clothing has been created, you will get an update on the request when its status changes", "anvithabl@gmail.com");

        } else {
            JOptionPane.showMessageDialog(this, Error);
        }
    }//GEN-LAST:event_btnSendRequestClothingActionPerformed

    private void txtNumberOfBedsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberOfBedsFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtNumberOfBeds.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtNumberOfBedsFocusLost

    private void txtVaccineCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVaccineCountFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtVaccineCount.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtVaccineCountFocusLost

    private void txtMedicalEquipCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalEquipCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalEquipCountActionPerformed

    private void txtMedicalEquipCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalEquipCountFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtMedicalEquipCount.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtMedicalEquipCountFocusLost

    private void txtBloodCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBloodCountFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtBloodCount.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtBloodCountFocusLost

    private void txtNumberOfCoverageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberOfCoverageFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtNumberOfCoverage.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtNumberOfCoverageFocusLost

    private void txtFoodBankServedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFoodBankServedFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtFoodBankServed.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtFoodBankServedFocusLost

    private void txtVehicleCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleCountFocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtVehicleCount.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtVehicleCountFocusLost

    private void txtNumberOfClothing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberOfClothing1FocusLost
        // TODO add your handling code here:
        boolean isChar = false;
        if (!evt.isTemporary()) {
            String key = txtNumberOfClothing1.getText();
            for (int i = 0; i < key.length(); i++) {
                if (!(key.charAt(i) >= '0'
                        && key.charAt(i) <= '9')) {
                    isChar = true;
                }
            }
            if (isChar) {
                JOptionPane.showMessageDialog(this, "enter only number");
            }
        }
    }//GEN-LAST:event_txtNumberOfClothing1FocusLost

    private void txtInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceCoverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceCoverageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequestBloodbank;
    private javax.swing.JButton btnSendRequestClothing;
    private javax.swing.JButton btnSendRequestFoodbank;
    private javax.swing.JButton btnSendRequestHospital;
    private javax.swing.JButton btnSendRequestMedicalEquip;
    private javax.swing.JButton btnSendRequestTransportation;
    private javax.swing.JButton btnSendRequestVaccine;
    private javax.swing.JButton btnSubmitRequestInsurance;
    private javax.swing.JComboBox<String> comboBoxBloodGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbMedicalEqupInventory;
    private javax.swing.JLabel lblBloodbankInventory;
    private javax.swing.JLabel lblFoodbankInventory;
    private javax.swing.JLabel lblFoodbankInventory1;
    private javax.swing.JLabel lblFoodbankInventory2;
    private javax.swing.JLabel lblHospitalInventory;
    private javax.swing.JLabel lblVaccineInventory1;
    private javax.swing.JLabel lblVaccineInventory2;
    private javax.swing.JPanel panelBloodbank;
    private javax.swing.JPanel panelClothing;
    private javax.swing.JPanel panelFoodbank;
    private javax.swing.JPanel panelHospital;
    private javax.swing.JPanel panelInsurance;
    private javax.swing.JPanel panelMedicalEquip;
    private javax.swing.JPanel panelTransportation;
    private javax.swing.JPanel panelVaccine;
    private javax.swing.JTextField txtBloodCount;
    private javax.swing.JTextField txtClothingLoc1;
    private javax.swing.JTextField txtFoodBankLoc;
    private javax.swing.JTextField txtFoodBankServed;
    private javax.swing.JTextField txtHospitalLoc;
    private javax.swing.JTextField txtInsuranceCoverage;
    private javax.swing.JTextField txtMedicalEquip;
    private javax.swing.JTextField txtMedicalEquipCount;
    private javax.swing.JTextField txtNumberOfBeds;
    private javax.swing.JTextField txtNumberOfClothing1;
    private javax.swing.JTextField txtNumberOfCoverage;
    private javax.swing.JTextField txtVaccine;
    private javax.swing.JTextField txtVaccineCount;
    private javax.swing.JTextField txtVehicleCount;
    private javax.swing.JTextField txtVehicleType;
    // End of variables declaration//GEN-END:variables
}
